// Code generated by go-vk from vk.xml at 2024-10-03 15:43:53.965153 +0200 CEST m=+1.894160918. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
