// Code generated by go-vk from vk.xml at 2024-10-03 15:43:54.293973 +0200 CEST m=+2.222981251. DO NOT EDIT.

package vk

// ExportMetalObjectTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExportMetalObjectTypeFlagsEXT.html
type ExportMetalObjectTypeFlagsEXT Flags

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
