// Code generated by go-vk from vk.xml at 2024-10-03 15:43:54.229063 +0200 CEST m=+2.158071376. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
