//go:build darwin

// Code generated by go-vk from vk.xml at 2024-10-03 15:43:54.103536 +0200 CEST m=+2.032543876. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
